sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      sudo: required
      dist: xenial
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=linters
    - python: 3.6
      env: TOXENV=pyscf
    - python: 3.6
      env: TOXENV=iodata
  fast_finish: true
  allow_failures:
    - python: 3.6
      env: TOXENV=pyscf
    - python: 3.6
      env: TOXENV=iodata
install: pip install tox codecov
script: tox
after_success:
  - codecov
