sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=qa
    - python: 3.7
      sudo: required
      dist: xenial
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=optional
  allow_failures:
    - python: 3.6
      env: TOXENV=optional
install: pip install tox
script: tox
